# frozen_string_literal: true

source "https://rubygems.org"

ruby ">= 3.2.0"

gem "bootsnap", require: false
gem "bcrypt", "~> 3.1"
gem "dotenv-rails", groups: %i[development test]
gem "pg", "~> 1.5"
gem "puma", ">= 6.0"
gem "rails", "~> 8.0.0"
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
